#!/usr/bin/env bash
set -euo pipefail

# fetch-pr-reviews.sh
# Fetches PR metadata and unresolved review comments from GitHub via gh CLI.
#
# Exit codes:
#   0 - Success
#   1 - No PR found for current branch
#   2 - Missing required tools (gh or jq)
#   3 - GitHub API error

# --- Dependency check ---
for cmd in gh jq; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "{\"error\": \"Missing required tool: $cmd\"}" >&2
    exit 2
  fi
done

# --- Fetch PR metadata ---
pr_json=$(gh pr view --json number,title,url,headRefName,baseRefName,reviewDecision 2>/dev/null) || {
  echo "{\"error\": \"No pull request found for the current branch.\"}" >&2
  exit 1
}

number=$(echo "$pr_json" | jq -r '.number')
title=$(echo "$pr_json" | jq -r '.title')
url=$(echo "$pr_json" | jq -r '.url')
head_branch=$(echo "$pr_json" | jq -r '.headRefName')
base_branch=$(echo "$pr_json" | jq -r '.baseRefName')
review_decision=$(echo "$pr_json" | jq -r '.reviewDecision // "PENDING"')

if [ -z "$number" ] || [ "$number" = "null" ]; then
  echo "{\"error\": \"Could not parse PR number from gh output.\"}" >&2
  exit 1
fi

# --- Resolve repo owner/name ---
repo=$(gh repo view --json nameWithOwner -q '.nameWithOwner' 2>/dev/null) || {
  echo "{\"error\": \"Could not resolve repository.\"}" >&2
  exit 3
}

# --- Fetch review comments (inline, on diffs) ---
# Uses the pulls review-comments API which returns all inline comments
review_comments_json=$(gh api "repos/${repo}/pulls/${number}/comments" --paginate 2>/dev/null) || {
  echo "{\"error\": \"Failed to fetch review comments from GitHub API.\"}" >&2
  exit 3
}

# --- Fetch issue comments (general, on the PR conversation) ---
issue_comments_json=$(gh api "repos/${repo}/issues/${number}/comments" --paginate 2>/dev/null) || {
  echo "{\"error\": \"Failed to fetch issue comments from GitHub API.\"}" >&2
  exit 3
}

# --- Fetch reviews (top-level review bodies) ---
reviews_json=$(gh api "repos/${repo}/pulls/${number}/reviews" --paginate 2>/dev/null) || {
  echo "{\"error\": \"Failed to fetch reviews from GitHub API.\"}" >&2
  exit 3
}

# --- Format output ---
result=$(jq -n \
  --argjson review_comments "$review_comments_json" \
  --argjson issue_comments "$issue_comments_json" \
  --argjson reviews "$reviews_json" \
  --arg number "$number" \
  --arg title "$title" \
  --arg url "$url" \
  --arg head_branch "$head_branch" \
  --arg base_branch "$base_branch" \
  --arg review_decision "$review_decision" \
'
  # Inline review comments — unresolved threads only
  # GitHub groups threads by in_reply_to_id; root comments have no in_reply_to_id
  # A thread is "resolved" if its root comment has a non-null pull_request_review_id
  # that maps to a DISMISSED review, but the simplest signal is checking the
  # "subject_type" and grouping.

  # Build a map of comment_id -> comment for threading
  ($review_comments | map({(.id | tostring): .}) | add // {}) as $comment_map |

  # Find root comments (no in_reply_to_id) that are not outdated/resolved
  [
    $review_comments[]
    | select(.in_reply_to_id == null)
    | . as $root
    | {
        type: "inline",
        id: (.id | tostring),
        file: .path,
        line: (.original_line // .line // null),
        side: (.side // "RIGHT"),
        diff_hunk: .diff_hunk,
        notes: (
          [$root | {
            author: .user.login,
            body: .body,
            created_at: .created_at,
            updated_at: .updated_at
          }] +
          [$review_comments[]
            | select(.in_reply_to_id == ($root.id))
            | {
                author: .user.login,
                body: .body,
                created_at: .created_at,
                updated_at: .updated_at
              }
          ]
        )
      }
  ] as $inline |

  # General issue comments (conversation tab)
  [
    $issue_comments[]
    | select(.user.type != "Bot" or (.body | test("generated by|auto-generated"; "i") | not))
    | {
        type: "general",
        id: (.id | tostring),
        file: null,
        line: null,
        notes: [{
          author: .user.login,
          body: .body,
          created_at: .created_at,
          updated_at: .updated_at
        }]
      }
  ] as $general |

  # Top-level review bodies (CHANGES_REQUESTED, COMMENTED with body)
  [
    $reviews[]
    | select(.body != null and .body != "" and .state != "DISMISSED")
    | {
        type: "review",
        id: (.id | tostring),
        state: .state,
        file: null,
        line: null,
        notes: [{
          author: .user.login,
          body: .body,
          created_at: .submitted_at,
          updated_at: .submitted_at
        }]
      }
  ] as $review_bodies |

  {
    pr: {
      number: ($number | tonumber),
      title: $title,
      url: $url,
      head_branch: $head_branch,
      base_branch: $base_branch,
      review_decision: $review_decision
    },
    summary: {
      inline_comments: ($inline | length),
      general_comments: ($general | length),
      review_bodies: ($review_bodies | length),
      total: (($inline | length) + ($general | length) + ($review_bodies | length))
    },
    discussions: ($inline + $review_bodies + $general)
  }
')

echo "$result"
